version: 2.1
orbs:
  continuation: circleci/continuation@0.2.0
  
jobs:
  generate-config:
    executor: continuation/default
    steps:
      - checkout
      - run:
          name: Generate Pipeline generated_config.yml file
          command: |
            chmod +x ./scripts/generate-pipeline-config.sh |
            sh ./scripts/generate-pipeline-config.sh << pipeline.git.branch >>
      - continuation/continue:
          parameters: '{}'
          configuration_path: configs/generated_config.yml
workflows:
  setup-workflow:
    jobs:
      - generate-config
